---
title: "Coupon Code"
type: "exercise"  # challenge, exercise, article, tutorial, video
description: "'Click Here' for a coupon for 50% off!"
tags: "javascript, dom-manipulation, events"
ignore:
- "coupon-code.md"
